# Gemfile for testing the Tron gem
source 'https://rubygems.org'

gem 'tron.rb', '~> 1.0.7'
gem 'dotenv', '~> 2.7' # For environment variable management

# Only include minitest if you want to run tests as well
group :test do
  gem 'minitest', '~> 5.0'
  gem 'rake', '~> 13.0'
end