name: Tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }} - Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [2.7, 3.0, 3.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Run tests
      run: |
        bundle exec rake test