# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv", "~> 2.8"
gem "base58"
gem "rbsecp256k1", "~> 5.1"
gem "keccak", "~> 1.3"

group :development, :test do
  gem "bundler", "~> 2.4"
  gem "rake", "~> 13.0"
  gem "minitest", "~> 5.0"
  gem "minitest-reporters", "~> 1.4"
end