# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv", "~> 2.8"
gem "base58"

group :development, :test do
  gem "bundler", "~> 2.0"
  gem "rake", "~> 13.0"
  gem "minitest", "~> 5.0"
  gem "minitest-reporters", "~> 1.4"
end