# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

task :default => :test

desc "Build the gem"
task :build do
  system("gem", "build", "tron.gemspec")
end

desc "Install the gem"
task :install => :build do
  system("gem", "install", "tron.rb-#{File.read('lib/tron/version.rb').match(/VERSION = ['"](.+)['"]/)[1]}.gem")
end