name: Release

on:
  push:
    tags:
      - 'tron.rb-v*'

permissions:
  contents: write

jobs:
  release:
    name: Release to RubyGems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: tron/utilities/tron-wallet-toolkit/ruby
          ruby-version: 2.7
          bundler-cache: true

      - name: Install dependencies
        working-directory: tron/utilities/tron-wallet-toolkit/ruby
        run: |
          bundle install

      - name: Run tests
        working-directory: tron/utilities/tron-wallet-toolkit/ruby
        run: |
          bundle exec rake test

      - name: Build gem
        working-directory: tron/utilities/tron-wallet-toolkit/ruby
        run: |
          gem build tron.gemspec

      - name: Push gem to RubyGems
        working-directory: tron/utilities/tron-wallet-toolkit/ruby
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: tron/utilities/tron-wallet-toolkit/ruby/*.gem
          generate_release_notes: true